name: Label Automation 

on:
  pull_request:
    types:
      - closed 
  pull_request_target: 
    types: 
      - closed 

jobs:
  remove:
    name: Remove outdated Labels
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'in progress')
    steps:
      - run: sleep 60
      - uses: mondeja/remove-labels-gh-action@v1.1.1
        with:
          token: "${{ secrets.WORKFLOW_TOKEN }}"
          labels: in progress
