name: Label Automation

on:
  pull_request_target:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  done:
    name: Mark as Done
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0
        with: 
          config-path: .github/labeler_done.yml
          config-repo: Julexar/RPG-Master
          github-token: "${{ secrets.WORKFLOW_TOKEN }}"