name: Label Automation

on:
  pull_request: 
    types:
      - synchronize

jobs:
  label:
    name: Mark as In Progress
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0
        with:
          config-path: .github/labeler_wip.yml
          config-repo: Julexar/RPG-Master
          github-token: "${{ secrets.WORKFLOW_TOKEN }}"
