name: Label Automation

on:
  pull_request_target:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  label:
    name: Mark as Done
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: srvaroa/labeler@v1.10.0
        with: 
          config_path: .github/labeler_done.yml
        env:
          GITHUB_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
