name: Milestone Automation

on:
  issues:
    types:
      - opened

jobs:
  add:
    name: Add Milestone to Issue
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/milestone-add-action@v0.0.1
        with:
          action-token: ${{ secrets.WORKFLOW_TOKEN }}
          co-milestones: >
            {
              "[ISSUE]":"Finish Bot",
              "[IDEA]":"Finish Bot"
            }
