name: Milestone Automation

on:
  issues:
    types:
      - opened
      - synchronize
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Hex/auto-milestone-binder@v1.0.3
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
