name: Project Automation

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  scrap:
    name: Mark as Scrapped
    if: contains(github.event.issue.state_reason, 'planned') || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: Julexar/Update-Project-Column@v1.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          url: 'https://github.com/users/Julexar/projects/7/views/1'
          column: 'Scrapped'
          label: 'wontfix'
          
  done:
    name: Mark as Done
    if: github.event.issue.state_reason == 'completed'
    runs-on: ubuntu-latest
    steps:
      - uses: Julexar/Update-Project-Column@v1.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          url: 'https://github.com/users/Julexar/projects/7/views/1'
          column: 'Scrapped'