name: Project PR Automation

on:
  pull_request:
    types: [labeled]

jobs:
  scrap_wontfix:
    name: Scrap PR (wont fix)
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'wontfix' }}
    steps:
      - uses: pauldruziak/move-labeled-or-milestoned-pull-request@v1.0.2
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "Scrapped"
          label-name: "wontfix"
          columns-to-ignore: "Done"
          
  scrap_duplicate:
    name: Scrap PR (duplicate)
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'duplicate' }}
    steps:
      - uses: pauldruziak/move-labeled-or-milestoned-pull-request@v1.0.2
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "Scrapped"
          label-name: "duplicate"
          columns-to-ignore: "Done"
          
  mark_as_wip:
    name: Mark PR as W.I.P
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'in progress' }}
    steps:
      - uses: pauldruziak/move-labeled-or-milestoned-pull-request@v1.0.2
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "In Progress"
          label-name: "in progress"
          columns-to-ignore: "Done"
