name: Project Issue Automation

on:
  issues:
    types: [labeled]

jobs:
  scrap_wontfix:
    name: Scrap Issue (wont fix)
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'wontfix' }}
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "Scrapped"
          label-name: "wontfix"
          columns-to-ignore: "Done"
          
  scrap_duplicate:
    name: Scrap Issue (duplicate)
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'duplicate' }}
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "Scrapped"
          label-name: "duplicate"
          columns-to-ignore: "Done"
          
  mark_as_wip:
    name: Mark Issue as W.I.P
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'in progress' }}
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.WORKFLOW_TOKEN }}"
          project-url: "https://github.com/users/Julexar/projects/7"
          column-name: "In Progress"
          label-name: "in progress"
          columns-to-ignore: "Done"
